### ISSUE TITLE
Paging is not required

### ISSUE THREAD

**Issue by Bubasick** [evilsquirr3l/eShop#78]
Instead, I propose you to make a controller, that would have next query params: take, skip. Back-end should not know about "Current Page" or "Pages". It is an Angular-side logic

**Comment by evilsquirr3l** [comment]
I don't see any difference between the method that takes take/skip or the current page/page size. In the first scenario, to get 50-100 products, you send a request with (50, 50), in the second scenario you send a request with (2, 50)

**Comment by Bubasick** [comment]
I see a difference in redundant code. Why would API care about paging? It is simply not its job. I think API should be page agnostic and just deliver objects that are filtered/sorted (if it is not a simple sorting which can be performed UI-side, there is also nuances. If sorting can be done on UI I think its better to perform it there, because there will be less CPU usage by our application). Skip and take are more then enough for paging
