### ISSUE TITLE
Why do we need all of those values here?

### ISSUE THREAD

**Issue by Bubasick** [evilsquirr3l/eShop#81]
https://github.com/evilsquirr3l/eShop/blob/365dcb1e381adf941970e93fd80ad0a5c94e3a07/WebApi/ClientApp/src/app/eshop/models/baseType.ts#L5

**Comment by evilsquirr3l** [comment]
We need this for the admin dashboard in the future. 
For property isDeleted: If the regular user tries to get the entity with isDeleted = true, he gets 404. If the admin tries to get this entity, he gets the entity and can restore it.
For createdAt / modifiedAt: I hope I'll do something like "When the entity was deleted / who did this" for admin dashboard
