### ISSUE TITLE
I suppose you still don't know the actual designs of your application 

### ISSUE THREAD

**Issue by Bubasick** [evilsquirr3l/eShop#82]
https://github.com/evilsquirr3l/eShop/blob/365dcb1e381adf941970e93fd80ad0a5c94e3a07/WebApi/ClientApp/src/app/eshop/models/product.ts#L10
Instead of rushing it, maybe try to develop some kind of mock-ups for the reference. It can be hard to keep everything in your head. Might be refactoring the code a lot in the end

**Comment by evilsquirr3l** [comment]
We know exactly what the database schema for the eShop is, it's described here: https://fabric.inc/blog/ecommerce-database-design-example/
All these models from frontend are the same as DTOs in the backend, so they will be changed at the same time or won't be changed at all.

**Comment by Bubasick** [comment]
I mean't not the schema, but UX part and designs. How user interacts with the interface. Why I asked it, because most of the time, you don't need to map all the loaded data to UI from backend.
